from typing import Any, Dict, List, Optional, Protocol


class LearningSessionRepositoryPort(Protocol):
    def start(self, owner_id: str, session: Dict[str, Any], question: Dict[str, Any], sources: List[Dict[str, Any]]) -> Dict[str, Any]: ...
    def record_attempt(self, owner_id: str, attempt: Dict[str, Any], next_question: Optional[Dict[str, Any]]) -> Dict[str, Any]: ...
    def resume(self, owner_id: str, session_id: Optional[str] = None) -> Dict[str, Any]: ...
    def complete(self, owner_id: str, session_id: str, summary: Optional[str]) -> Dict[str, Any]: ...
    def list_due_reviews(self, owner_id: str, limit: int) -> List[Dict[str, Any]]: ...
    def record_review(self, owner_id: str, review: Dict[str, Any]) -> Dict[str, Any]: ...
    def stage_knowledge_candidates(self, owner_id: str, session_id: str, candidates: List[Dict[str, Any]]) -> List[Dict[str, Any]]: ...
    def list_knowledge_candidates(self, owner_id: str, session_id: str) -> List[Dict[str, Any]]: ...
    def review_knowledge_candidate(self, owner_id: str, candidate_id: str, approved: bool, note: Optional[str]) -> Dict[str, Any]: ...


class UuidFactory(Protocol):
    def __call__(self) -> str: ...
